### ISSUE TITLE
Crate test cluster does not work with 3.2.3 version

### ISSUE THREAD

**Issue by Pradeepnitw** [crate/crate-java-testing#62]
when we try to run crate test cluster with 3.2.3 we are facing with the following error. The crate-testing version that we are using is 0.6.1. But can be reproducible with any version.

```
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at io.crate.testing.Utils.uncompressTarGZ(Utils.java:158)
	at io.crate.testing.CrateTestCluster.prepareEnvironment(CrateTestCluster.java:329)
	at io.crate.testing.CrateTestCluster.before(CrateTestCluster.java:301)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```
After debugging this issue, found that it errors out in uncompressTarGZ method of Utils.java when the first file that arrives in the iteration is not a directory.

By adding the below code in the method, we were able to resolve the issue.

```
        if(dest.isDirectory()) {
          dest.mkdirs();
        }
```

**Comment by mfussenegger** [comment]
Thank you for the report and sorry for the late reply. 

Is this still an issue with the current latest version (0.7) ?
