### ISSUE TITLE
Failing Test Cases

### ISSUE THREAD

**Issue by chughpiyush** [crate/crate-java-testing#65]
The current master branch's code is failing while running tests. 2 tests are failing:

1. The one in `FromLatestUrlTest` class.

```
Unrecognized option: -Xlog:gc*,gc+age=trace,safepoint:file=/tmp/crate.testing/working/crate-url-64e0ecfcc6feecb926e99c58ab33225975c5ea70_9b1ba3db-a2a6-4ca2-8253-b66ba93f77f3/logs/gc.log:utctime,pid,tags:filecount=16,filesize=64m
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

```

```
Crate Test Cluster not started completely
java.lang.IllegalStateException: Crate Test Cluster not started completely
	at __randomizedtesting.SeedInfo.seed([AAE55A85B12F6772]:0)
	at io.crate.testing.CrateTestCluster.startCluster(CrateTestCluster.java:336)
	at io.crate.testing.CrateTestCluster.before(CrateTestCluster.java:319)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:365)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:798)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$2.evaluate(ThreadLeakControl.java:401)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSuite(RandomizedRunner.java:642)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.access$200(RandomizedRunner.java:129)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$1.run(RandomizedRunner.java:559)
Caused by: java.util.concurrent.TimeoutException: Cluster has not been started within 30 seconds
	at io.crate.testing.CrateTestCluster.waitUntilClusterIsReady(CrateTestCluster.java:267)
	at io.crate.testing.CrateTestCluster.startCluster(CrateTestCluster.java:333)
	... 9 more

```

2. `testJDK8IsUsedForCrateLt3_2` in `CrateTestServerTests` class:

```
Expected: a string containing "1.8"
     but: was "/usr/lib/jvm/.java-8-oracle.jinfo"
java.lang.AssertionError: 
Expected: a string containing "1.8"
     but: was "/usr/lib/jvm/.java-8-oracle.jinfo"
	at __randomizedtesting.SeedInfo.seed([D8BC2EBC0E9CAD39:68931AA14C215A9]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at io.crate.testing.CrateTestServerTests.testJDK8IsUsedForCrateLt3_2(CrateTestServerTests.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1618)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:827)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
```

I can give a fix in a Pull Request for the (2)nd case, but for the (1)st case I am not sure, because it is failing in the latest nightly build of CrateDB and there might be an issue in that. I suspect some `String[] command` issue in the latest nightly build. No other test case in the whole application uses the `String[] command` like the one used by this test:

```
            settings.put("discovery.seed_hosts", Utils.join(unicastHosts, ","));
            settings.put("cluster.initial_master_nodes", Utils.join(unicastHosts, ","));
```

**Comment by mfussenegger** [comment]
Regarding 1)

Do you have a JDK >= 11 available on the system running the tests?

CrateDB 4.0 requires JDK 11+. The `Unrecognized option:` error comes from a older JVM not recognizing the garbage collection logging option that we set. (They've changed in JDK 9 if I remember correctly, we used to have a compatibility layer for that, but removed it since we don't support JAVA < 11 anymore).

Regarding 2) 

Would be nice if you could open up a PR with a fix.

**Comment by chughpiyush** [comment]
This issue can be closed now.
